
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SocialApps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class CategoriesOwnership
{

    public Nullable<int> OwnerID { get; set; }

    public int OwneeID { get; set; }

    public long ID { get; set; }

}

}
