//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesCategories
    {
        public int ExpenseID { get; set; }
        public int CategoryID { get; set; }
        public long ID { get; set; }
    
        public virtual Categories Categories { get; set; }
        public virtual Operations Operations { get; set; }
    }
}
