//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ExpensesLinks
    {
        public int ExpenseID { get; set; }
        public int LinkID { get; set; }
        public long ID { get; set; }
    
        public virtual Links Links { get; set; }
        public virtual Operations Operations { get; set; }
    }
}
