//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Expenses
    {
        public int ID { get; set; }
        public System.DateTime Date { get; set; }
        public Nullable<double> Cost { get; set; }
        public byte[] LastUpdate { get; set; }
        public string Note { get; set; }
        public System.Guid DataOwner { get; set; }
        public Nullable<bool> Monthly { get; set; }
        public Nullable<System.DateTime> FirstMonth { get; set; }
        public Nullable<System.DateTime> LastMonth { get; set; }
        public string Currency { get; set; }
        public Nullable<short> Rating { get; set; }
        public Nullable<short> Importance { get; set; }
        public string EncryptedName { get; set; }
        public Nullable<int> NameChecksum { get; set; }
        public string Project { get; set; }
        public string Name { get; set; }
    }
}
