
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SocialApps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class ExpensesLinks
{

    public int ExpenseID { get; set; }

    public int LinkID { get; set; }

    public long ID { get; set; }



    public virtual Links Links { get; set; }

    public virtual Operations Operations { get; set; }

}

}
