//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SocialApps.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Links
    {
        public Links()
        {
            this.ExpensesLinks = new HashSet<ExpensesLinks>();
        }
    
        public int ID { get; set; }
        public string URL { get; set; }
        public string Name { get; set; }
        public System.Guid DataOwner { get; set; }
    
        public virtual ICollection<ExpensesLinks> ExpensesLinks { get; set; }
    }
}
