
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SocialApps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Links
{

    public Links()
    {

        this.ExpensesLinks = new HashSet<ExpensesLinks>();

    }


    public int ID { get; set; }

    public string URL { get; set; }

    public string Name { get; set; }

    public System.Guid DataOwner { get; set; }



    public virtual ICollection<ExpensesLinks> ExpensesLinks { get; set; }

}

}
