
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SocialApps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Month
{

    public int ID { get; set; }

    public Nullable<decimal> Budget { get; set; }

    public Nullable<decimal> Income { get; set; }

    public System.Guid DataOwner { get; set; }

    public int Year { get; set; }

    public int Month1 { get; set; }

    public string Currency { get; set; }

}

}
