
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace SocialApps.Models
{

using System;
    using System.Collections.Generic;
    
public partial class Strings
{

    public int ID { get; set; }

    public int LangId { get; set; }

    public int ControlId { get; set; }

    public string Text { get; set; }



    public virtual Controls Controls { get; set; }

    public virtual Languages Languages { get; set; }

}

}
