//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option or rebuild the Visual Studio project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to For more information visit application homepage at &lt;strong&gt;&lt;a href=&quot;https://dvmorozov.github.io/expenses/&quot; target=&quot;_blank&quot;&gt;GitHub&lt;/a&gt;&lt;/strong&gt; or
        ///		&lt;strong&gt;&lt;a href=&quot;https://www.facebook.com/expensestracking/&quot; target=&quot;_blank&quot;&gt;application page&lt;/a&gt;&lt;/strong&gt; at Facebook..
        /// </summary>
        internal static string AboutForMoreInfo {
            get {
                return ResourceManager.GetString("AboutForMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Facebook account by.
        /// </summary>
        internal static string AboutFromFacebook {
            get {
                return ResourceManager.GetString("AboutFromFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from Google Chrome by.
        /// </summary>
        internal static string AboutFromGoogleChrome {
            get {
                return ResourceManager.GetString("AboutFromGoogleChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to from mobile devices by.
        /// </summary>
        internal static string AboutFromMobileDevice {
            get {
                return ResourceManager.GetString("AboutFromMobileDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for interest to this application!.
        /// </summary>
        internal static string AboutThanks {
            get {
                return ResourceManager.GetString("AboutThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You can use the app.
        /// </summary>
        internal static string AboutYouCanUseTheApp {
            get {
                return ResourceManager.GetString("AboutYouCanUseTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t login by the service..
        /// </summary>
        internal static string AccountCantLogin {
            get {
                return ResourceManager.GetString("AccountCantLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pets,Food,Fuel,Home,Car,Loans,Mobile,Internet,Clothing,Medicine,Gifts,Amusements,Taxes,Interior,Household,Transport,Education,Sport.
        /// </summary>
        internal static string AccountCategories {
            get {
                return ResourceManager.GetString("AccountCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Check email to reset password..
        /// </summary>
        internal static string AccountCheckEmail {
            get {
                return ResourceManager.GetString("AccountCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to login.
        /// </summary>
        internal static string AccountClickToLogin {
            get {
                return ResourceManager.GetString("AccountClickToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click to logout.
        /// </summary>
        internal static string AccountClickToLogout {
            get {
                return ResourceManager.GetString("AccountClickToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string AccountConfirmPassword {
            get {
                return ResourceManager.GetString("AccountConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection form.
        /// </summary>
        internal static string AccountConnectionForm {
            get {
                return ResourceManager.GetString("AccountConnectionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect with your {0} account..
        /// </summary>
        internal static string AccountConnectWithYour {
            get {
                return ResourceManager.GetString("AccountConnectWithYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email confirmation.
        /// </summary>
        internal static string AccountEmailConfirmation {
            get {
                return ResourceManager.GetString("AccountEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot password?.
        /// </summary>
        internal static string AccountForgotPassword {
            get {
                return ResourceManager.GetString("AccountForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input code.
        /// </summary>
        internal static string AccountInputCode {
            get {
                return ResourceManager.GetString("AccountInputCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Input email.
        /// </summary>
        internal static string AccountInputEmail {
            get {
                return ResourceManager.GetString("AccountInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login failure.
        /// </summary>
        internal static string AccountLoginFailure {
            get {
                return ResourceManager.GetString("AccountLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with.
        /// </summary>
        internal static string AccountLoginWith {
            get {
                return ResourceManager.GetString("AccountLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password confirmation.
        /// </summary>
        internal static string AccountPasswordConfirmation {
            get {
                return ResourceManager.GetString("AccountPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your password has been reset..
        /// </summary>
        internal static string AccountPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("AccountPasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember in browser.
        /// </summary>
        internal static string AccountRemember {
            get {
                return ResourceManager.GetString("AccountRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remember me.
        /// </summary>
        internal static string AccountRememberMe {
            get {
                return ResourceManager.GetString("AccountRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password.
        /// </summary>
        internal static string AccountResetPassword {
            get {
                return ResourceManager.GetString("AccountResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset password confirmation.
        /// </summary>
        internal static string AccountResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("AccountResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select authentication provider:.
        /// </summary>
        internal static string AccountSelectProvider {
            get {
                return ResourceManager.GetString("AccountSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send code.
        /// </summary>
        internal static string AccountSendCodeTitle {
            get {
                return ResourceManager.GetString("AccountSendCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send link by email.
        /// </summary>
        internal static string AccountSendLinkByEmail {
            get {
                return ResourceManager.GetString("AccountSendLinkByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string AccountSignUp {
            get {
                return ResourceManager.GetString("AccountSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for email confirmation..
        /// </summary>
        internal static string AccountThankYouForEmail {
            get {
                return ResourceManager.GetString("AccountThankYouForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify code.
        /// </summary>
        internal static string AccountVerifyCode {
            get {
                return ResourceManager.GetString("AccountVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You successfully passed &lt;strong&gt;{0}&lt;/strong&gt; authentication. Input your user name and press the &quot;Register&quot; button to complete the operation..
        /// </summary>
        internal static string AccountYouSuccessfullyPassed {
            get {
                return ResourceManager.GetString("AccountYouSuccessfullyPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add expense.
        /// </summary>
        internal static string AddExpenseTitle {
            get {
                return ResourceManager.GetString("AddExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add income.
        /// </summary>
        internal static string AddIncomeTitle {
            get {
                return ResourceManager.GetString("AddIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add new receipt.
        /// </summary>
        internal static string AddReceipt {
            get {
                return ResourceManager.GetString("AddReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add rest of receipt.
        /// </summary>
        internal static string AddRestOfReceipt {
            get {
                return ResourceManager.GetString("AddRestOfReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another month.
        /// </summary>
        internal static string AnotherMonth {
            get {
                return ResourceManager.GetString("AnotherMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Asset.
        /// </summary>
        internal static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance by month for last {0} yrs.
        /// </summary>
        internal static string BalanceByMonth {
            get {
                return ResourceManager.GetString("BalanceByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string BalanceTitle {
            get {
                return ResourceManager.GetString("BalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Budget.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Contribute.
        /// </summary>
        internal static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day expenses.
        /// </summary>
        internal static string DayExpensesTitle {
            get {
                return ResourceManager.GetString("DayExpensesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decrypting.
        /// </summary>
        internal static string Decrypting {
            get {
                return ResourceManager.GetString("Decrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Discard Password.
        /// </summary>
        internal static string DiscardPassword {
            get {
                return ResourceManager.GetString("DiscardPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string DocListTitle {
            get {
                return ResourceManager.GetString("DocListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit category.
        /// </summary>
        internal static string EditCategoryTitle {
            get {
                return ResourceManager.GetString("EditCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit expense.
        /// </summary>
        internal static string EditExpenseTitle {
            get {
                return ResourceManager.GetString("EditExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit income.
        /// </summary>
        internal static string EditIncomeTitle {
            get {
                return ResourceManager.GetString("EditIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypt All.
        /// </summary>
        internal static string EncryptAll {
            get {
                return ResourceManager.GetString("EncryptAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encrypting.
        /// </summary>
        internal static string Encrypting {
            get {
                return ResourceManager.GetString("Encrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Encryption.
        /// </summary>
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you change the password ONLY NEW DATA will be encrypted with it. Old data will stay encrypted by previous passwords.
        ///										You should keep all passwords you were using to decrypt them..
        /// </summary>
        internal static string EncryptionIfYouChange {
            get {
                return ResourceManager.GetString("EncryptionIfYouChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New data won&apos;t be encrypted, but encrypted data will remain..
        /// </summary>
        internal static string EncryptionNewData {
            get {
                return ResourceManager.GetString("EncryptionNewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only data which were encrypted with this password will become readable..
        /// </summary>
        internal static string EncryptionOnlyData {
            get {
                return ResourceManager.GetString("EncryptionOnlyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup or confirmation failed. Try to set up the password again..
        /// </summary>
        internal static string EncryptionPassFailed {
            get {
                return ResourceManager.GetString("EncryptionPassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your responsibility to protect the password from being stolen. We will NEVER ASK you to disclose this password..
        /// </summary>
        internal static string EncryptionProtect {
            get {
                return ResourceManager.GetString("EncryptionProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat input to set up a new password. Any subsequent data will be encrypted with this password..
        /// </summary>
        internal static string EncryptionRepeatInput {
            get {
                return ResourceManager.GetString("EncryptionRepeatInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to It&apos;s your responsibility to remember the password. If you forget the password your data encrypted by it will be lost..
        /// </summary>
        internal static string EncryptionResponsibility {
            get {
                return ResourceManager.GetString("EncryptionResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set and Decrypt.
        /// </summary>
        internal static string EncryptionSetAndDecrypt {
            get {
                return ResourceManager.GetString("EncryptionSetAndDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set New Password.
        /// </summary>
        internal static string EncryptionSetNewPassword {
            get {
                return ResourceManager.GetString("EncryptionSetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set up the password to decrypt data..
        /// </summary>
        internal static string EncryptionSetUpPassword {
            get {
                return ResourceManager.GetString("EncryptionSetUpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to We DO NOT STORE this password at the server. It is active only until you close this site in your browser..
        /// </summary>
        internal static string EncryptionWeDontStore {
            get {
                return ResourceManager.GetString("EncryptionWeDontStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You need to set up and confirm the password before that operation..
        /// </summary>
        internal static string EncryptionYouNeedToSetUpOrConfirm {
            get {
                return ResourceManager.GetString("EncryptionYouNeedToSetUpOrConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sorry, an error occurred while processing your request..
        /// </summary>
        internal static string ErrorSorry {
            get {
                return ResourceManager.GetString("ErrorSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select expense.
        /// </summary>
        internal static string ExpensesByCategoryTitle {
            get {
                return ResourceManager.GetString("ExpensesByCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expense history.
        /// </summary>
        internal static string ExpensesHistoryTitle {
            get {
                return ResourceManager.GetString("ExpensesHistoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Firts month.
        /// </summary>
        internal static string FirstMonth {
            get {
                return ResourceManager.GetString("FirstMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forever.
        /// </summary>
        internal static string Forever {
            get {
                return ResourceManager.GetString("Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to History.
        /// </summary>
        internal static string History {
            get {
                return ResourceManager.GetString("History", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance.
        /// </summary>
        internal static string Importance {
            get {
                return ResourceManager.GetString("Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance report on.
        /// </summary>
        internal static string ImportanceReportTitle {
            get {
                return ResourceManager.GetString("ImportanceReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last {0} yrs.
        /// </summary>
        internal static string LastYears {
            get {
                return ResourceManager.GetString("LastYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Liability.
        /// </summary>
        internal static string Liability {
            get {
                return ResourceManager.GetString("Liability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account disabled..
        /// </summary>
        internal static string LockoutDisabled {
            get {
                return ResourceManager.GetString("LockoutDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Account disabled.
        /// </summary>
        internal static string LockoutTitle {
            get {
                return ResourceManager.GetString("LockoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Try again later..
        /// </summary>
        internal static string LockoutTryAgain {
            get {
                return ResourceManager.GetString("LockoutTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Day expenses.
        /// </summary>
        internal static string MainMenuDayExpenses {
            get {
                return ResourceManager.GetString("MainMenuDayExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New expense.
        /// </summary>
        internal static string MainMenuNewExpense {
            get {
                return ResourceManager.GetString("MainMenuNewExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string MainMenuReports {
            get {
                return ResourceManager.GetString("MainMenuReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main menu.
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add phone number.
        /// </summary>
        internal static string ManageAddPhoneNumber {
            get {
                return ResourceManager.GetString("ManageAddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change password.
        /// </summary>
        internal static string ManageChangePassword {
            get {
                return ResourceManager.GetString("ManageChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm password.
        /// </summary>
        internal static string ManageConfirmPassword {
            get {
                return ResourceManager.GetString("ManageConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete login {0} from your account.
        /// </summary>
        internal static string ManageDeleteLogin {
            get {
                return ResourceManager.GetString("ManageDeleteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External logins.
        /// </summary>
        internal static string ManageExternalLogins {
            get {
                return ResourceManager.GetString("ManageExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login with {0}.
        /// </summary>
        internal static string ManageLoginWith {
            get {
                return ResourceManager.GetString("ManageLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password.
        /// </summary>
        internal static string ManageNewPassword {
            get {
                return ResourceManager.GetString("ManageNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old password.
        /// </summary>
        internal static string ManageOldPassword {
            get {
                return ResourceManager.GetString("ManageOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Phone number.
        /// </summary>
        internal static string ManagePhoneNumber {
            get {
                return ResourceManager.GetString("ManagePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registered logins.
        /// </summary>
        internal static string ManageRegisteredLogins {
            get {
                return ResourceManager.GetString("ManageRegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two-factor authentication.
        /// </summary>
        internal static string ManageTwoFactorAuth {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify phone number.
        /// </summary>
        internal static string ManageVerifyPhone {
            get {
                return ResourceManager.GetString("ManageVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum file size is {0} megabytes.
        /// </summary>
        internal static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month budget.
        /// </summary>
        internal static string MonthBudgetTitle {
            get {
                return ResourceManager.GetString("MonthBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month income.
        /// </summary>
        internal static string MonthIncomeTitle {
            get {
                return ResourceManager.GetString("MonthIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Necessary.
        /// </summary>
        internal static string Necessary {
            get {
                return ResourceManager.GetString("Necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New category.
        /// </summary>
        internal static string NewCategoryTitle {
            get {
                return ResourceManager.GetString("NewCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New expense.
        /// </summary>
        internal static string NewExpenseTitle {
            get {
                return ResourceManager.GetString("NewExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New income.
        /// </summary>
        internal static string NewIncome {
            get {
                return ResourceManager.GetString("NewIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New income.
        /// </summary>
        internal static string NewIncomeTitle {
            get {
                return ResourceManager.GetString("NewIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No expenses found for.
        /// </summary>
        internal static string NoExpenseFound {
            get {
                return ResourceManager.GetString("NoExpenseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overdraft.
        /// </summary>
        internal static string Overdraft {
            get {
                return ResourceManager.GetString("Overdraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pie.
        /// </summary>
        internal static string Pie {
            get {
                return ResourceManager.GetString("Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pleasure.
        /// </summary>
        internal static string Pleasure {
            get {
                return ResourceManager.GetString("Pleasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait....
        /// </summary>
        internal static string ProgressBarWait {
            get {
                return ResourceManager.GetString("ProgressBarWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Balance.
        /// </summary>
        internal static string ReportBalance {
            get {
                return ResourceManager.GetString("ReportBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Importance.
        /// </summary>
        internal static string ReportImportance {
            get {
                return ResourceManager.GetString("ReportImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 Categories.
        /// </summary>
        internal static string ReportTop10Categories {
            get {
                return ResourceManager.GetString("ReportTop10Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top 10 categories of.
        /// </summary>
        internal static string ReportTop10Of {
            get {
                return ResourceManager.GetString("ReportTop10Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend By Category.
        /// </summary>
        internal static string ReportTrendByCategory {
            get {
                return ResourceManager.GetString("ReportTrendByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trend Overall.
        /// </summary>
        internal static string ReportTrendOverall {
            get {
                return ResourceManager.GetString("ReportTrendOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel receipt.
        /// </summary>
        internal static string ResetReceipt {
            get {
                return ResourceManager.GetString("ResetReceipt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Residue.
        /// </summary>
        internal static string Residue {
            get {
                return ResourceManager.GetString("Residue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        internal static string SelectCategoryTitle {
            get {
                return ResourceManager.GetString("SelectCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Select currency.
        /// </summary>
        internal static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chars.
        /// </summary>
        internal static string SelectCurrencyChars {
            get {
                return ResourceManager.GetString("SelectCurrencyChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Codes.
        /// </summary>
        internal static string SelectCurrencyCodes {
            get {
                return ResourceManager.GetString("SelectCurrencyCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expenses.
        /// </summary>
        internal static string SelectExpenseTitle {
            get {
                return ResourceManager.GetString("SelectExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomes.
        /// </summary>
        internal static string SelectIncomeTitle {
            get {
                return ResourceManager.GetString("SelectIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set password.
        /// </summary>
        internal static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Show more.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Spent.
        /// </summary>
        internal static string Spent {
            get {
                return ResourceManager.GetString("Spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Totals by month for last {0} yrs.
        /// </summary>
        internal static string TotalsByMonth {
            get {
                return ResourceManager.GetString("TotalsByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined.
        /// </summary>
        internal static string Undefined {
            get {
                return ResourceManager.GetString("Undefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unnecessary.
        /// </summary>
        internal static string Unnecessary {
            get {
                return ResourceManager.GetString("Unnecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uploaded documents.
        /// </summary>
        internal static string UploadedDocuments {
            get {
                return ResourceManager.GetString("UploadedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verify.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 year.
        /// </summary>
        internal static string Year1 {
            get {
                return ResourceManager.GetString("Year1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 years.
        /// </summary>
        internal static string Year10 {
            get {
                return ResourceManager.GetString("Year10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 10 yrs.
        /// </summary>
        internal static string Year10Short {
            get {
                return ResourceManager.GetString("Year10Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 yr.
        /// </summary>
        internal static string Year1Short {
            get {
                return ResourceManager.GetString("Year1Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 years.
        /// </summary>
        internal static string Year2 {
            get {
                return ResourceManager.GetString("Year2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2 yrs.
        /// </summary>
        internal static string Year2Short {
            get {
                return ResourceManager.GetString("Year2Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 years.
        /// </summary>
        internal static string Year5 {
            get {
                return ResourceManager.GetString("Year5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 yrs.
        /// </summary>
        internal static string Year5Short {
            get {
                return ResourceManager.GetString("Year5Short", resourceCulture);
            }
        }
    }
}
