//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.42000
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // класс с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить элемент, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте проект Visual Studio.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Web.Application.StronglyTypedResourceProxyBuilder", "14.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, используемый этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Resources", global::System.Reflection.Assembly.Load("App_GlobalResources"));
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Переопределяет свойство CurrentUICulture текущего потока для всех
        ///   подстановки ресурсов с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как For more information visit application homepage at &lt;strong&gt;&lt;a href=&quot;http://townbreath.com&quot; target=&quot;_blank&quot;&gt;townbreath.com&lt;/a&gt;&lt;/strong&gt; or
        ///		&lt;strong&gt;&lt;a href=&quot;https://www.facebook.com/expensestracking/&quot; target=&quot;_blank&quot;&gt;application page&lt;/a&gt;&lt;/strong&gt; at Facebook..
        /// </summary>
        internal static string AboutForMoreInfo {
            get {
                return ResourceManager.GetString("AboutForMoreInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как from Facebook account by.
        /// </summary>
        internal static string AboutFromFacebook {
            get {
                return ResourceManager.GetString("AboutFromFacebook", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как from Google Chrome by.
        /// </summary>
        internal static string AboutFromGoogleChrome {
            get {
                return ResourceManager.GetString("AboutFromGoogleChrome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как from mobile devices by.
        /// </summary>
        internal static string AboutFromMobileDevice {
            get {
                return ResourceManager.GetString("AboutFromMobileDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Thanks for interest to this application!.
        /// </summary>
        internal static string AboutThanks {
            get {
                return ResourceManager.GetString("AboutThanks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как About.
        /// </summary>
        internal static string AboutTitle {
            get {
                return ResourceManager.GetString("AboutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как You can use the app.
        /// </summary>
        internal static string AboutYouCanUseTheApp {
            get {
                return ResourceManager.GetString("AboutYouCanUseTheApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Account.
        /// </summary>
        internal static string Account {
            get {
                return ResourceManager.GetString("Account", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Can&apos;t login by the service..
        /// </summary>
        internal static string AccountCantLogin {
            get {
                return ResourceManager.GetString("AccountCantLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Check email to reset password..
        /// </summary>
        internal static string AccountCheckEmail {
            get {
                return ResourceManager.GetString("AccountCheckEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Click to login.
        /// </summary>
        internal static string AccountClickToLogin {
            get {
                return ResourceManager.GetString("AccountClickToLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Click to logout.
        /// </summary>
        internal static string AccountClickToLogout {
            get {
                return ResourceManager.GetString("AccountClickToLogout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Confirm password.
        /// </summary>
        internal static string AccountConfirmPassword {
            get {
                return ResourceManager.GetString("AccountConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Connection form.
        /// </summary>
        internal static string AccountConnectionForm {
            get {
                return ResourceManager.GetString("AccountConnectionForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Connect with your {0} account..
        /// </summary>
        internal static string AccountConnectWithYour {
            get {
                return ResourceManager.GetString("AccountConnectWithYour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Email confirmation.
        /// </summary>
        internal static string AccountEmailConfirmation {
            get {
                return ResourceManager.GetString("AccountEmailConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Forgot password?.
        /// </summary>
        internal static string AccountForgotPassword {
            get {
                return ResourceManager.GetString("AccountForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Input code.
        /// </summary>
        internal static string AccountInputCode {
            get {
                return ResourceManager.GetString("AccountInputCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Input email.
        /// </summary>
        internal static string AccountInputEmail {
            get {
                return ResourceManager.GetString("AccountInputEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Login failure.
        /// </summary>
        internal static string AccountLoginFailure {
            get {
                return ResourceManager.GetString("AccountLoginFailure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Login with.
        /// </summary>
        internal static string AccountLoginWith {
            get {
                return ResourceManager.GetString("AccountLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Password confirmation.
        /// </summary>
        internal static string AccountPasswordConfirmation {
            get {
                return ResourceManager.GetString("AccountPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Your password has been reset..
        /// </summary>
        internal static string AccountPasswordHasBeenReset {
            get {
                return ResourceManager.GetString("AccountPasswordHasBeenReset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Remember in browser.
        /// </summary>
        internal static string AccountRemember {
            get {
                return ResourceManager.GetString("AccountRemember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Remember me.
        /// </summary>
        internal static string AccountRememberMe {
            get {
                return ResourceManager.GetString("AccountRememberMe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Reset password.
        /// </summary>
        internal static string AccountResetPassword {
            get {
                return ResourceManager.GetString("AccountResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Reset password confirmation.
        /// </summary>
        internal static string AccountResetPasswordConfirmation {
            get {
                return ResourceManager.GetString("AccountResetPasswordConfirmation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select authentication provider:.
        /// </summary>
        internal static string AccountSelectProvider {
            get {
                return ResourceManager.GetString("AccountSelectProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Send code.
        /// </summary>
        internal static string AccountSendCodeTitle {
            get {
                return ResourceManager.GetString("AccountSendCodeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Send link by email.
        /// </summary>
        internal static string AccountSendLinkByEmail {
            get {
                return ResourceManager.GetString("AccountSendLinkByEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Sign Up.
        /// </summary>
        internal static string AccountSignUp {
            get {
                return ResourceManager.GetString("AccountSignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Thank you for email confirmation..
        /// </summary>
        internal static string AccountThankYouForEmail {
            get {
                return ResourceManager.GetString("AccountThankYouForEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Verify code.
        /// </summary>
        internal static string AccountVerifyCode {
            get {
                return ResourceManager.GetString("AccountVerifyCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как You successfully passed &lt;strong&gt;{0}&lt;/strong&gt; authentication. Input your user name and press the &quot;Register&quot; button to complete the operation..
        /// </summary>
        internal static string AccountYouSuccessfullyPassed {
            get {
                return ResourceManager.GetString("AccountYouSuccessfullyPassed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Add expense.
        /// </summary>
        internal static string AddExpenseTitle {
            get {
                return ResourceManager.GetString("AddExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Add income.
        /// </summary>
        internal static string AddIncomeTitle {
            get {
                return ResourceManager.GetString("AddIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Amount.
        /// </summary>
        internal static string Amount {
            get {
                return ResourceManager.GetString("Amount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Another month.
        /// </summary>
        internal static string AnotherMonth {
            get {
                return ResourceManager.GetString("AnotherMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Asset.
        /// </summary>
        internal static string Asset {
            get {
                return ResourceManager.GetString("Asset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Attention.
        /// </summary>
        internal static string Attention {
            get {
                return ResourceManager.GetString("Attention", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Balance by month for last {0} yrs.
        /// </summary>
        internal static string BalanceByMonth {
            get {
                return ResourceManager.GetString("BalanceByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Balance.
        /// </summary>
        internal static string BalanceTitle {
            get {
                return ResourceManager.GetString("BalanceTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Bar.
        /// </summary>
        internal static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Budget.
        /// </summary>
        internal static string Budget {
            get {
                return ResourceManager.GetString("Budget", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Category.
        /// </summary>
        internal static string Category {
            get {
                return ResourceManager.GetString("Category", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Code.
        /// </summary>
        internal static string Code {
            get {
                return ResourceManager.GetString("Code", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Contribute.
        /// </summary>
        internal static string Contribute {
            get {
                return ResourceManager.GetString("Contribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Create.
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Currency.
        /// </summary>
        internal static string Currency {
            get {
                return ResourceManager.GetString("Currency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Day expenses.
        /// </summary>
        internal static string DayExpensesTitle {
            get {
                return ResourceManager.GetString("DayExpensesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Decrypting.
        /// </summary>
        internal static string Decrypting {
            get {
                return ResourceManager.GetString("Decrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Details.
        /// </summary>
        internal static string Details {
            get {
                return ResourceManager.GetString("Details", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Discard Password.
        /// </summary>
        internal static string DiscardPassword {
            get {
                return ResourceManager.GetString("DiscardPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Documents.
        /// </summary>
        internal static string DocListTitle {
            get {
                return ResourceManager.GetString("DocListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Edit category.
        /// </summary>
        internal static string EditCategoryTitle {
            get {
                return ResourceManager.GetString("EditCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Edit expense.
        /// </summary>
        internal static string EditExpenseTitle {
            get {
                return ResourceManager.GetString("EditExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Edit income.
        /// </summary>
        internal static string EditIncomeTitle {
            get {
                return ResourceManager.GetString("EditIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Email.
        /// </summary>
        internal static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Encrypt All.
        /// </summary>
        internal static string EncryptAll {
            get {
                return ResourceManager.GetString("EncryptAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Encrypting.
        /// </summary>
        internal static string Encrypting {
            get {
                return ResourceManager.GetString("Encrypting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Encryption.
        /// </summary>
        internal static string Encryption {
            get {
                return ResourceManager.GetString("Encryption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как If you change the password ONLY NEW DATA will be encrypted with it. Old data will stay encrypted by previous passwords.
        ///										You should keep all passwords you were using to decrypt them..
        /// </summary>
        internal static string EncryptionIfYouChange {
            get {
                return ResourceManager.GetString("EncryptionIfYouChange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как New data won&apos;t be encrypted, but encrypted data will remain..
        /// </summary>
        internal static string EncryptionNewData {
            get {
                return ResourceManager.GetString("EncryptionNewData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Only data which were encrypted with this password will become readable..
        /// </summary>
        internal static string EncryptionOnlyData {
            get {
                return ResourceManager.GetString("EncryptionOnlyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Setup or confirmation failed. Try to set up the password again..
        /// </summary>
        internal static string EncryptionPassFailed {
            get {
                return ResourceManager.GetString("EncryptionPassFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как It&apos;s your responsibility to protect the password from being stolen. We will NEVER ASK you to disclose this password..
        /// </summary>
        internal static string EncryptionProtect {
            get {
                return ResourceManager.GetString("EncryptionProtect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Repeat input to set up a new password. Any subsequent data will be encrypted with this password..
        /// </summary>
        internal static string EncryptionRepeatInput {
            get {
                return ResourceManager.GetString("EncryptionRepeatInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как It&apos;s your responsibility to remember the password. If you forget the password your data encrypted by it will be lost..
        /// </summary>
        internal static string EncryptionResponsibility {
            get {
                return ResourceManager.GetString("EncryptionResponsibility", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Set and Decrypt.
        /// </summary>
        internal static string EncryptionSetAndDecrypt {
            get {
                return ResourceManager.GetString("EncryptionSetAndDecrypt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Set New Password.
        /// </summary>
        internal static string EncryptionSetNewPassword {
            get {
                return ResourceManager.GetString("EncryptionSetNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Set up the password to decrypt data..
        /// </summary>
        internal static string EncryptionSetUpPassword {
            get {
                return ResourceManager.GetString("EncryptionSetUpPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как We DO NOT STORE this password at the server. It is active only until you close this site in your browser..
        /// </summary>
        internal static string EncryptionWeDontStore {
            get {
                return ResourceManager.GetString("EncryptionWeDontStore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как You need to set up and confirm the password before that operation..
        /// </summary>
        internal static string EncryptionYouNeedToSetUpOrConfirm {
            get {
                return ResourceManager.GetString("EncryptionYouNeedToSetUpOrConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Error.
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Sorry, an error occurred while processing your request..
        /// </summary>
        internal static string ErrorSorry {
            get {
                return ResourceManager.GetString("ErrorSorry", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Expense.
        /// </summary>
        internal static string Expense {
            get {
                return ResourceManager.GetString("Expense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select expense.
        /// </summary>
        internal static string ExpensesByCategoryTitle {
            get {
                return ResourceManager.GetString("ExpensesByCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Firts month.
        /// </summary>
        internal static string FirstMonth {
            get {
                return ResourceManager.GetString("FirstMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Forever.
        /// </summary>
        internal static string Forever {
            get {
                return ResourceManager.GetString("Forever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Home.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Importance.
        /// </summary>
        internal static string Importance {
            get {
                return ResourceManager.GetString("Importance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Importance report on.
        /// </summary>
        internal static string ImportanceReportTitle {
            get {
                return ResourceManager.GetString("ImportanceReportTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Income.
        /// </summary>
        internal static string Income {
            get {
                return ResourceManager.GetString("Income", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Last month.
        /// </summary>
        internal static string LastMonth {
            get {
                return ResourceManager.GetString("LastMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Last {0} yrs.
        /// </summary>
        internal static string LastYears {
            get {
                return ResourceManager.GetString("LastYears", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Liability.
        /// </summary>
        internal static string Liability {
            get {
                return ResourceManager.GetString("Liability", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Account disabled..
        /// </summary>
        internal static string LockoutDisabled {
            get {
                return ResourceManager.GetString("LockoutDisabled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Account disabled.
        /// </summary>
        internal static string LockoutTitle {
            get {
                return ResourceManager.GetString("LockoutTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Try again later..
        /// </summary>
        internal static string LockoutTryAgain {
            get {
                return ResourceManager.GetString("LockoutTryAgain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Logout.
        /// </summary>
        internal static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Day expenses.
        /// </summary>
        internal static string MainMenuDayExpenses {
            get {
                return ResourceManager.GetString("MainMenuDayExpenses", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как New expense.
        /// </summary>
        internal static string MainMenuNewExpense {
            get {
                return ResourceManager.GetString("MainMenuNewExpense", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Reports.
        /// </summary>
        internal static string MainMenuReports {
            get {
                return ResourceManager.GetString("MainMenuReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Main menu.
        /// </summary>
        internal static string MainMenuTitle {
            get {
                return ResourceManager.GetString("MainMenuTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Add phone number.
        /// </summary>
        internal static string ManageAddPhoneNumber {
            get {
                return ResourceManager.GetString("ManageAddPhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Change password.
        /// </summary>
        internal static string ManageChangePassword {
            get {
                return ResourceManager.GetString("ManageChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Confirm password.
        /// </summary>
        internal static string ManageConfirmPassword {
            get {
                return ResourceManager.GetString("ManageConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Delete login {0} from your account.
        /// </summary>
        internal static string ManageDeleteLogin {
            get {
                return ResourceManager.GetString("ManageDeleteLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как External logins.
        /// </summary>
        internal static string ManageExternalLogins {
            get {
                return ResourceManager.GetString("ManageExternalLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Login with {0}.
        /// </summary>
        internal static string ManageLoginWith {
            get {
                return ResourceManager.GetString("ManageLoginWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как New password.
        /// </summary>
        internal static string ManageNewPassword {
            get {
                return ResourceManager.GetString("ManageNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Old password.
        /// </summary>
        internal static string ManageOldPassword {
            get {
                return ResourceManager.GetString("ManageOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Phone number.
        /// </summary>
        internal static string ManagePhoneNumber {
            get {
                return ResourceManager.GetString("ManagePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Registered logins.
        /// </summary>
        internal static string ManageRegisteredLogins {
            get {
                return ResourceManager.GetString("ManageRegisteredLogins", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Two-factor authentication.
        /// </summary>
        internal static string ManageTwoFactorAuth {
            get {
                return ResourceManager.GetString("ManageTwoFactorAuth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Verify phone number.
        /// </summary>
        internal static string ManageVerifyPhone {
            get {
                return ResourceManager.GetString("ManageVerifyPhone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Maximum file size is {0} megabytes.
        /// </summary>
        internal static string MaxFileSize {
            get {
                return ResourceManager.GetString("MaxFileSize", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Month budget.
        /// </summary>
        internal static string MonthBudgetTitle {
            get {
                return ResourceManager.GetString("MonthBudgetTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Month income.
        /// </summary>
        internal static string MonthIncomeTitle {
            get {
                return ResourceManager.GetString("MonthIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Monthly.
        /// </summary>
        internal static string Monthly {
            get {
                return ResourceManager.GetString("Monthly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Necessary.
        /// </summary>
        internal static string Necessary {
            get {
                return ResourceManager.GetString("Necessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как New category.
        /// </summary>
        internal static string NewCategoryTitle {
            get {
                return ResourceManager.GetString("NewCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как New expense.
        /// </summary>
        internal static string NewExpenseTitle {
            get {
                return ResourceManager.GetString("NewExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как New income.
        /// </summary>
        internal static string NewIncome {
            get {
                return ResourceManager.GetString("NewIncome", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как New income.
        /// </summary>
        internal static string NewIncomeTitle {
            get {
                return ResourceManager.GetString("NewIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как No expenses found for.
        /// </summary>
        internal static string NoExpenseFound {
            get {
                return ResourceManager.GetString("NoExpenseFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как None.
        /// </summary>
        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Note.
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Number.
        /// </summary>
        internal static string Number {
            get {
                return ResourceManager.GetString("Number", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Overdraft.
        /// </summary>
        internal static string Overdraft {
            get {
                return ResourceManager.GetString("Overdraft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pie.
        /// </summary>
        internal static string Pie {
            get {
                return ResourceManager.GetString("Pie", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Pleasure.
        /// </summary>
        internal static string Pleasure {
            get {
                return ResourceManager.GetString("Pleasure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Please wait....
        /// </summary>
        internal static string ProgressBarWait {
            get {
                return ResourceManager.GetString("ProgressBarWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Project.
        /// </summary>
        internal static string Project {
            get {
                return ResourceManager.GetString("Project", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Rating.
        /// </summary>
        internal static string Rating {
            get {
                return ResourceManager.GetString("Rating", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Register.
        /// </summary>
        internal static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Registration.
        /// </summary>
        internal static string Registration {
            get {
                return ResourceManager.GetString("Registration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Repeat.
        /// </summary>
        internal static string Repeat {
            get {
                return ResourceManager.GetString("Repeat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Balance.
        /// </summary>
        internal static string ReportBalance {
            get {
                return ResourceManager.GetString("ReportBalance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Importance.
        /// </summary>
        internal static string ReportImportance {
            get {
                return ResourceManager.GetString("ReportImportance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Reports.
        /// </summary>
        internal static string ReportsTitle {
            get {
                return ResourceManager.GetString("ReportsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Top 10 Categories.
        /// </summary>
        internal static string ReportTop10Categories {
            get {
                return ResourceManager.GetString("ReportTop10Categories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Top 10 categories of.
        /// </summary>
        internal static string ReportTop10Of {
            get {
                return ResourceManager.GetString("ReportTop10Of", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Trend By Category.
        /// </summary>
        internal static string ReportTrendByCategory {
            get {
                return ResourceManager.GetString("ReportTrendByCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Trend Overall.
        /// </summary>
        internal static string ReportTrendOverall {
            get {
                return ResourceManager.GetString("ReportTrendOverall", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Rest.
        /// </summary>
        internal static string Rest {
            get {
                return ResourceManager.GetString("Rest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Save.
        /// </summary>
        internal static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Categories.
        /// </summary>
        internal static string SelectCategoryTitle {
            get {
                return ResourceManager.GetString("SelectCategoryTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Select currency.
        /// </summary>
        internal static string SelectCurrency {
            get {
                return ResourceManager.GetString("SelectCurrency", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Chars.
        /// </summary>
        internal static string SelectCurrencyChars {
            get {
                return ResourceManager.GetString("SelectCurrencyChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Codes.
        /// </summary>
        internal static string SelectCurrencyCodes {
            get {
                return ResourceManager.GetString("SelectCurrencyCodes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Expenses.
        /// </summary>
        internal static string SelectExpenseTitle {
            get {
                return ResourceManager.GetString("SelectExpenseTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Incomes.
        /// </summary>
        internal static string SelectIncomeTitle {
            get {
                return ResourceManager.GetString("SelectIncomeTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Send.
        /// </summary>
        internal static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Set password.
        /// </summary>
        internal static string SetPassword {
            get {
                return ResourceManager.GetString("SetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Setup.
        /// </summary>
        internal static string Setup {
            get {
                return ResourceManager.GetString("Setup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Show more.
        /// </summary>
        internal static string ShowMore {
            get {
                return ResourceManager.GetString("ShowMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Sign Up.
        /// </summary>
        internal static string SignUp {
            get {
                return ResourceManager.GetString("SignUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Spent.
        /// </summary>
        internal static string Spent {
            get {
                return ResourceManager.GetString("Spent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Totals by month for last {0} yrs.
        /// </summary>
        internal static string TotalsByMonth {
            get {
                return ResourceManager.GetString("TotalsByMonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Unnecessary.
        /// </summary>
        internal static string Unnecessary {
            get {
                return ResourceManager.GetString("Unnecessary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Update.
        /// </summary>
        internal static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Upload.
        /// </summary>
        internal static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Uploaded documents.
        /// </summary>
        internal static string UploadedDocuments {
            get {
                return ResourceManager.GetString("UploadedDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как Verify.
        /// </summary>
        internal static string Verify {
            get {
                return ResourceManager.GetString("Verify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 1 year.
        /// </summary>
        internal static string Year1 {
            get {
                return ResourceManager.GetString("Year1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 10 years.
        /// </summary>
        internal static string Year10 {
            get {
                return ResourceManager.GetString("Year10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 10 yrs.
        /// </summary>
        internal static string Year10Short {
            get {
                return ResourceManager.GetString("Year10Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 1 yr.
        /// </summary>
        internal static string Year1Short {
            get {
                return ResourceManager.GetString("Year1Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 2 years.
        /// </summary>
        internal static string Year2 {
            get {
                return ResourceManager.GetString("Year2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 2 yrs.
        /// </summary>
        internal static string Year2Short {
            get {
                return ResourceManager.GetString("Year2Short", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 5 years.
        /// </summary>
        internal static string Year5 {
            get {
                return ResourceManager.GetString("Year5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, такую же, как 5 yrs.
        /// </summary>
        internal static string Year5Short {
            get {
                return ResourceManager.GetString("Year5Short", resourceCulture);
            }
        }
    }
}
