USE [expenses].EXPENSES
GO

SELECT TOP(1000) * 
FROM [expenses].EXPENSES 
JOIN [expenses].EXPENSESCATEGORIES
ON ID = EXPENSEID
JOIN [expenses].CATEGORIES AS C ON CATEGORYID = C.ID
WHERE CATEGORYID = 33
ORDER BY DATE DESC